# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8210cc6df89383d5194d175b07d5f971ba9f0a38c46abeac98f09945dcfe39e1035bf9645e141cae1ba53dd2929aadbbbc626a5c5684844426eb95ba7b3b13b8

test:
  secret_key_base: e603d7f1ccc194ce8fc55f8634496a9d1d3fc7bc261fac5a69b765e9849a7e87ee82385d5ba42770750e35bf2090a4490d67a768725ff9c453fd983c61130dbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
